import { useState } from "react";
import Head from "next/head";
import Banner from "../components/Banner";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [btnText, setBtnText] = useState("Get Started");

  const handleOnClick = () => {
    setBtnText("Clicked");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
      </Head>

      <main className={styles.main}>
        <Banner btnText={btnText} handleOnClick={handleOnClick} />
      </main>

      <footer className={styles.footer}>
        Copyright © 2021 Coffee Connoisseur
      </footer>
    </div>
  );
}
